// Generated by CoffeeScript 1.3.3
var app, assets, express, http;

express = require('express');

assets = require('connect-assets');

http = require('http');

app = express();

app.configure(function() {
  app.set('port', process.env.PORT || 3000);
  app.set('views', process.cwd() + '/views');
  app.set('view engine', 'jade');
  app.use(assets());
  app.use(express.favicon());
  app.use(express.logger('dev'));
  app.use(express.bodyParser());
  app.use(express.methodOverride());
  app.use(app.router);
  return app.use(express["static"](process.cwd() + '/public'));
});

app.configure('development', function() {
  return app.use(express.errorHandler());
});

app.get('/', function(req, resp) {
  return resp.render('index');
});

app.get('/pages/*', function(req, resp) {
  return resp.render('pages/' + req.params[0]);
});

http.createServer(app).listen(app.get('port'), function() {
  return console.log("Express server listening on port " + app.get('port'));
});
